title: Enhance That
url: https://enhancethat.fashion
baseurl: ""  # custom domain, so keep empty

collections:
  blog:
    output: true
    permalink: /blog/:slug/

defaults:
  - scope:
      path: "blog"
      type: "blog"
    values:
      layout: blog_post
      author: Enhance That
      permalink: /blog/:basename/

excerpt_separator: "<!--more-->"